const profiles = [
  {
    name: 'Ray Simar',
    avatar: '/assets/ray-simar.jpeg',
    title: 'Professor in the Practice',
    organization: 'Department of ECE at Rice University',
    roles: ['Project Inspiration', 'Project Advisor', 'Fourier-based Analysis'],
    link: 'https://profiles.rice.edu/faculty/ray-simar',
  },
  {
    name: 'I-No Liao',
    avatar: '/assets/ino-liao.jpeg',
    title: 'Master of Computer Science',
    organization: 'Rice University',
    roles: ['Web Dev', 'COVID-19 Data', 'Tableau UI'],
    link: 'https://inoliao.info/',
  },
  {
    name: 'Vinicius Da Silva',
    avatar: '/assets/vini-da-silva.jpeg',
    title: 'PhD Candidate',
    organization: 'Rice University',
    roles: ['COVID-19 Data', 'Network Modeling'],
    link: 'https://www.linkedin.com/in/vini-goncalves/',
  },
  {
    name: 'Chang-Yuan Shih',
    avatar: '/assets/changyuan-shih.jpg',
    title: 'Master of Computer Science',
    organization: 'Rice University',
    roles: ['Web Dev', 'Google Data Studio UI'],
    link: 'https://www.csie.ntu.edu.tw/~cyshih',
  },
  {
    name: 'Howard Lan',
    avatar: '/assets/howard.jpeg',
    title: 'Master of Computer Science',
    organization: 'Rice University',
    roles: ['Web Dev'],
    link: '',
  },
  {
    name: 'Chiao-Yu Pai',
    avatar: '/assets/chiaoyu-pai.jpeg',
    title: '',
    organization: 'Rice University',
    roles: ['COVID-19 Data', 'VM Administration'],
    link: '',
  },
  {
    name: 'Yu-Che Cheng',
    avatar: '/assets/yuche-cheng.png',
    title: '',
    organization: 'Rice University',
    roles: ['Fourier-based Analysis', 'Web Dev', 'Tableau UI'],
    link: '',
  },
  {
    name: 'Nicolae Sapoval',
    avatar: '/assets/nicolae-sapoval.jpeg',
    title: 'PhD Student',
    organization: 'Rice University',
    roles: ['Bioinformatics'],
    link: 'https://nsapoval.com',
  },
  {
    name: 'Xiaotong Lu',
    avatar: '/assets/xiaotong-lu.jpeg',
    title: '',
    organization: 'Rice University',
    roles: ['COVID-19 Data'],
    link: '',
  },
  {
    name: 'Qi Wang',
    avatar: '/assets/qj-wang.png',
    title: '',
    organization: 'Rice University',
    roles: ['Bioinformatics'],
    link: '',
  },
  {
    name: 'Wei Xia',
    avatar: '/assets/wei-xia.jpeg',
    title: '',
    organization: 'Rice University',
    roles: ['User Interface Design'],
    link: '',
  },
  {
    name: 'Xuyang Xiao',
    avatar: '/assets/xuyang-xiao.jpeg',
    title: '',
    organization: 'Rice University',
    roles: ['Web Dev'],
    link: '',
  },
  {
    name: 'Wenlong Yan',
    avatar: '/assets/wenlong-yan.jpg',
    title: 'Master of Computer Science',
    organization: 'Rice University',
    roles: ['Web Dev'],
    link: '',
  },
];

export default profiles;
